#!/bin/bash
# =============================================================================
# TradeSync — Cloud-Init VPS Setup Script
# =============================================================================
# HOW TO USE:
#   1. Push this project to a private GitHub/GitLab repo.
#   2. Fill in YOUR VALUES in the section below (lines marked  ← YOU SET THIS).
#   3. When creating your VPS (DigitalOcean, Hetzner, Vultr, Linode, etc.),
#      paste this entire file into the "User Data" field.
#   4. The VPS will install and start everything automatically on first boot.
#   5. Open http://<your-vps-ip> in your browser — done.
#
# You never need to SSH in or run any commands.
# =============================================================================

# =============================================================================
#  YOUR VALUES — fill these in before pasting
# =============================================================================

REPO_URL="https://github.com/YOUR_USERNAME/YOUR_REPO.git"   # ← YOU SET THIS
# If the repo is private, use a token URL:
# REPO_URL="https://YOUR_TOKEN@github.com/YOUR_USERNAME/YOUR_REPO.git"

# ── Required keys ─────────────────────────────────────────────────────────────
DATABASE_PASSWORD="CHANGE_ME_STRONG_PASSWORD"   # ← YOU SET THIS
SESSION_SECRET="CHANGE_ME"                       # ← YOU SET THIS  (openssl rand -hex 32)
COPY_API_SECRET="CHANGE_ME"                      # ← YOU SET THIS  (openssl rand -hex 24)
COPY_ENCRYPTION_KEY="CHANGE_ME"                  # ← YOU SET THIS  (openssl rand -hex 32)

# ── Optional keys (leave blank to disable the feature) ────────────────────────
GOOGLE_API_KEY=""           # Gemini AI signal validation
TELEGRAM_BOT_TOKEN=""       # Telegram notifications & signal parsing
EODHD_API_KEY=""            # Economic calendar (20 free calls/day)
REDIS_PASSWORD=""           # Leave blank for no Redis auth

# =============================================================================
#  END OF YOUR VALUES — do not edit below this line
# =============================================================================
set -euo pipefail
exec > /var/log/tradesync-setup.log 2>&1   # all output goes to this log

INSTALL_DIR="/opt/tradesync"
LOG_DIR="/var/log/tradesync"
DATA_DIR="/var/lib/tradesync"
DEPLOY_USER="tradesync"

echo "============================================================"
echo "  TradeSync — Cloud-Init Setup  $(date)"
echo "============================================================"

# ── 1. System packages ────────────────────────────────────────────────────────
echo "[1/9] Installing system packages…"

apt-get update -q
dpkg --add-architecture i386

# Node.js 20
curl -fsSL https://deb.nodesource.com/setup_20.x | bash - >/dev/null 2>&1

DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
  nodejs \
  python3 python3-pip \
  docker.io docker-compose-plugin \
  wine64 wine32 winetricks \
  xvfb x11-utils \
  supervisor \
  postgresql postgresql-contrib \
  git curl wget build-essential \
  libpq-dev ca-certificates gnupg

systemctl enable --now docker postgresql
echo "  ✓ System packages installed"

# ── 2. Clone repo ─────────────────────────────────────────────────────────────
echo "[2/9] Cloning repository…"

if [ -d "$INSTALL_DIR/.git" ]; then
  cd "$INSTALL_DIR" && git pull --ff-only
  echo "  ✓ Repository updated"
else
  git clone --depth=1 "$REPO_URL" "$INSTALL_DIR"
  echo "  ✓ Repository cloned to $INSTALL_DIR"
fi

# ── 3. Create system user, directories, and symlink ──────────────────────────
echo "[3/9] Creating user and directories…"

if ! id "$DEPLOY_USER" &>/dev/null; then
  useradd --system --no-create-home --shell /usr/sbin/nologin "$DEPLOY_USER"
fi

mkdir -p "$LOG_DIR" "$DATA_DIR/tg_sessions"
chmod 750 "$LOG_DIR"
chmod 700 "$DATA_DIR/tg_sessions"
chown -R "$DEPLOY_USER":"$DEPLOY_USER" "$LOG_DIR" "$DATA_DIR"
echo "  ✓ Directories ready"

# ── 4. Write .env ─────────────────────────────────────────────────────────────
echo "[4/9] Writing .env file…"

cat > "$INSTALL_DIR/.env" << ENVEOF
# Auto-generated by cloud-init on $(date)

DATABASE_URL=postgresql://tradesync:${DATABASE_PASSWORD}@localhost:5432/tradesync
SESSION_SECRET=${SESSION_SECRET}
GOOGLE_API_KEY=${GOOGLE_API_KEY}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
EODHD_API_KEY=${EODHD_API_KEY}

REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASSWORD}

COPY_API_HOST=0.0.0.0
COPY_API_PORT=8001
COPY_API_SECRET=${COPY_API_SECRET}
COPY_ENCRYPTION_KEY=${COPY_ENCRYPTION_KEY}

MT5_BRIDGE_HOST=127.0.0.1
MT5_BRIDGE_PORT=18812
MT5_POLL_INTERVAL=1.0
MT5_RECONNECT_ATTEMPTS=5
MT5_RECONNECT_DELAY=5.0

TELEGRAM_SESSION_DIR=/var/lib/tradesync/tg_sessions
WORKER_CONCURRENCY=4
WORKER_MAX_RETRIES=3
COPY_LOG_LEVEL=INFO

PORT=5000
NODE_ENV=production
PYTHON_BIN=/usr/bin/python3
ENVEOF

chmod 600 "$INSTALL_DIR/.env"
echo "  ✓ .env written"

# ── 5. PostgreSQL — database and user ─────────────────────────────────────────
echo "[5/9] Setting up PostgreSQL…"

sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='tradesync'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE USER tradesync WITH PASSWORD '${DATABASE_PASSWORD}';"

sudo -u postgres psql -lqt | cut -d\| -f1 | grep -qw tradesync || \
  sudo -u postgres psql -c "CREATE DATABASE tradesync OWNER tradesync;"

echo "  ✓ PostgreSQL database ready"

# ── 6. Node.js app — install deps and build ───────────────────────────────────
echo "[6/9] Building Node.js app…"

cd "$INSTALL_DIR"
npm ci --prefer-offline 2>/dev/null || npm install
npm run build

python3 -m pip install --quiet \
  -r "$INSTALL_DIR/python/copy_trading/requirements.txt"

echo "  ✓ Node.js app built"

# ── Node.js systemd service ───────────────────────────────────────────────────
cat > /etc/systemd/system/tradesync-app.service << SVCEOF
[Unit]
Description=TradeSync Trading Dashboard
After=network.target postgresql.service
Requires=postgresql.service

[Service]
Type=simple
User=$DEPLOY_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$INSTALL_DIR/.env
ExecStart=$(which node) dist/index.js
Restart=always
RestartSec=5
StandardOutput=append:$LOG_DIR/app.log
StandardError=append:$LOG_DIR/app_err.log

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable tradesync-app
systemctl start tradesync-app
echo "  ✓ tradesync-app service started"

# ── 7. Wine + MT5 terminal + mt5-remote bridge ────────────────────────────────
echo "[7/9] Setting up Wine / MT5 bridge…"

# Start a temporary virtual display for Wine installation
Xvfb :99 -screen 0 1024x768x16 &
XVFB_PID=$!
export DISPLAY=:99
export WINEDEBUG=-all
export WINEPREFIX="/root/.wine"
sleep 3

# Common Windows runtimes MT5 depends on
winetricks -q dotnet40 corefonts vcrun2019 2>/dev/null || true

# Python 3.9 for Windows inside Wine (mt5-remote server runs here)
if ! DISPLAY=:99 wine python --version &>/dev/null 2>&1; then
  PY_WIN_INSTALLER="/tmp/python-3.9.13-amd64.exe"
  wget -q -O "$PY_WIN_INSTALLER" \
    "https://www.python.org/ftp/python/3.9.13/python-3.9.13-amd64.exe"
  DISPLAY=:99 wine "$PY_WIN_INSTALLER" /quiet InstallAllUsers=0 PrependPath=1
  sleep 8
fi

DISPLAY=:99 wine python -m pip install --quiet --upgrade pip MetaTrader5 mt5-remote
echo "  ✓ MetaTrader5 + mt5-remote installed inside Wine"

# MT5 terminal
MT5_EXE="/root/.wine/drive_c/Program Files/MetaTrader 5/terminal64.exe"
if [ ! -f "$MT5_EXE" ]; then
  MT5_INSTALLER="/tmp/mt5setup.exe"
  wget -q -O "$MT5_INSTALLER" \
    "https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe"
  DISPLAY=:99 wine "$MT5_INSTALLER" /S
  sleep 15
fi

# Stop the temporary display
kill $XVFB_PID 2>/dev/null || true
echo "  ✓ MT5 terminal installed"

# ── 8. Supervisor — keeps Xvfb, MT5, bridge and copy engine alive ─────────────
echo "[8/9] Installing Supervisor configs…"

CT_DIR="$INSTALL_DIR/python/copy_trading"

cp "$CT_DIR/supervisor/mt5bridge.conf"  /etc/supervisor/conf.d/tradesync-mt5bridge.conf
cp "$CT_DIR/supervisor/copyengine.conf" /etc/supervisor/conf.d/tradesync-copyengine.conf
sed -i "s|/opt/tradesync|$INSTALL_DIR|g" /etc/supervisor/conf.d/tradesync-copyengine.conf

systemctl enable --now supervisor
supervisorctl reread
supervisorctl update
supervisorctl start xvfb mt5terminal mt5bridge copyengine 2>/dev/null || true
echo "  ✓ Supervisor services started"

# ── 9. Docker services — Redis + Copy API + Worker ───────────────────────────
echo "[9/9] Starting Docker services…"

cd "$INSTALL_DIR"
docker compose -f "$CT_DIR/docker-compose.yml" build --no-cache
docker compose -f "$CT_DIR/docker-compose.yml" up -d

# Systemd service to restart Docker services on reboot
cat > /etc/systemd/system/tradesync-bridge.service << BRIDGESVC
[Unit]
Description=TradeSync Copy Trading Bridge (Docker)
After=network.target docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$INSTALL_DIR
ExecStart=docker compose -f $CT_DIR/docker-compose.yml up -d
ExecStop=docker compose -f $CT_DIR/docker-compose.yml down
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
BRIDGESVC

systemctl daemon-reload
systemctl enable tradesync-bridge
echo "  ✓ Docker services started"

# ── Log rotation ──────────────────────────────────────────────────────────────
cat > /etc/logrotate.d/tradesync << 'LOGEOF'
/var/log/tradesync/*.log {
  daily
  rotate 14
  compress
  missingok
  notifempty
}
LOGEOF

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  TradeSync setup complete!  $(date)"
echo ""
echo "  Dashboard: http://$(curl -s ifconfig.me):5000"
echo ""
echo "  To configure copy trading accounts, open the dashboard"
echo "  and go to Copy Trading → Add Account. The MT5 bridge"
echo "  will log in to your broker automatically using the"
echo "  credentials you enter in the UI."
echo ""
echo "  All logs: /var/log/tradesync-setup.log"
echo "            /var/log/tradesync/app.log"
echo "            /var/log/tradesync/mt5bridge.log"
echo "============================================================"
