import { useState, useEffect } from 'react';
import { useLocation } from 'wouter';
import { usePublicTheme } from '@/context/PublicThemeContext';
import SEOHead from '@/components/SEOHead';

const F = "'DM Mono', 'Courier New', monospace";

const SECTIONS = ['Privacy Policy', 'Terms of Service', 'Contact & Support'] as const;
type Section = typeof SECTIONS[number];

/* ── shared doc primitives ─────────────────────────────────────────────────── */
function H1({ children, dm }: { children: React.ReactNode; dm: boolean }) {
  return (
    <h1 style={{ fontFamily: F, fontSize: 'clamp(0.9rem,1.6vw,1.1rem)', fontWeight: 700, color: dm ? '#e2e8f0' : '#0f172a', margin: '0 0 6px', letterSpacing: '-0.01em', lineHeight: 1.2 }}>
      {children}
    </h1>
  );
}

function Updated({ dm }: { dm: boolean }) {
  return (
    <p style={{ fontFamily: F, fontSize: 12, color: dm ? '#64748b' : '#94a3b8', margin: '0 0 40px' }}>
      Last Updated: 01/01/2025
    </p>
  );
}

function H2({ children, dm }: { children: React.ReactNode; dm: boolean }) {
  return (
    <h2 style={{ fontFamily: F, fontSize: 15, fontWeight: 700, color: dm ? '#e2e8f0' : '#0f172a', margin: '36px 0 10px', letterSpacing: '-0.01em' }}>
      {children}
    </h2>
  );
}

function P({ children, dm }: { children: React.ReactNode; dm: boolean }) {
  return (
    <p style={{ fontFamily: F, fontSize: 13, color: dm ? '#94a3b8' : '#374151', lineHeight: 1.9, margin: '0 0 14px' }}>
      {children}
    </p>
  );
}

function UL({ items, dm }: { items: string[]; dm: boolean }) {
  return (
    <ul style={{ margin: '0 0 16px', paddingLeft: 22, display: 'flex', flexDirection: 'column', gap: 8 }}>
      {items.map((item, i) => (
        <li key={i} style={{ fontFamily: F, fontSize: 13, color: dm ? '#94a3b8' : '#374151', lineHeight: 1.85 }}>{item}</li>
      ))}
    </ul>
  );
}

function Brand({ dm }: { dm: boolean }) {
  return (
    <span style={{ fontFamily: "'DM Serif Display', serif", fontWeight: 400, letterSpacing: '0.01em', whiteSpace: 'nowrap' }}>
      <span style={{ color: dm ? '#f1f5f9' : '#0f172a' }}>Myfm</span><span style={{ color: '#3b82f6' }}>journal</span>
    </span>
  );
}

/* ── Privacy Policy ─────────────────────────────────────────────────────────── */
function PrivacyContent({ dm }: { dm: boolean }) {
  return (
    <>
      <H1 dm={dm}>Privacy Policy</H1>
      <Updated dm={dm} />

      <P dm={dm}>
        <Brand dm={dm} /> ("we", "us", "our", or the "Platform") is committed to safeguarding the privacy of everyone who uses our services. This Privacy Policy describes how we collect, process, store, transfer, and protect your personal data when you access myfmjournal.com and any related web applications. By using our services you acknowledge that you have read and understood this policy.
      </P>

      <H2 dm={dm}>1. Information We Collect</H2>
      <P dm={dm}>We collect information you provide directly, data generated by your use of the platform, and technical signals from your devices.</P>
      <UL dm={dm} items={[
        'Account Information — Name, email address, hashed password, country, and account creation timestamp.',
        'Journal & Trade Data — Trade entries including symbol, entry/exit prices, lot size, P&L, notes, screenshots, strategy tags, and psychological annotations.',
        'Session & Analytics Data — Features used, time on each panel, click patterns, and error logs.',
        'Device & Network Information — IP address, browser type, operating system, and timezone for security and fraud prevention.',
        'Communication Data — Messages sent to our support team and feedback you submit.',
        'Payment Information — Billing details are handled by our third-party processor. We do not store full card numbers on our servers.',
        'Automatically Collected Data — Cookies, local storage tokens, and session identifiers.',
      ]} />

      <H2 dm={dm}>2. How We Use Your Information</H2>
      <UL dm={dm} items={[
        'To provide, operate, and maintain the journal, analytics, AI coach, and economic calendar.',
        'To authenticate your identity and protect your account from unauthorised access.',
        'To process subscription payments and send billing notifications.',
        'To respond to support tickets and account enquiries.',
        'To analyze aggregated, anonymised usage patterns for product improvement.',
        'To detect and prevent fraud, abuse, and security incidents.',
        'To comply with applicable legal and regulatory obligations.',
        'To send service announcements and security alerts. You may opt out of non-essential communications at any time.',
      ]} />

      <H2 dm={dm}>3. Legal Basis for Processing (GDPR)</H2>
      <P dm={dm}>If you are in the EEA or UK, our processing relies on the following legal bases under GDPR:</P>
      <UL dm={dm} items={[
        'Contract Performance — Processing necessary to deliver the services you have registered for.',
        'Legitimate Interests — Security monitoring, fraud prevention, and analytics, where these do not override your rights.',
        'Legal Obligation — Compliance with applicable laws including financial record-keeping regulations.',
        'Consent — For optional communications such as newsletters. You may withdraw consent at any time.',
      ]} />

      <H2 dm={dm}>4. Data Security</H2>
      <P dm={dm}>
        All data in transit is encrypted using TLS 1.2 or higher. Data at rest is encrypted using AES-256. Access to production systems is restricted to authorised personnel with multi-factor authentication. We conduct periodic security audits and vulnerability assessments. In the event of a confirmed data breach we will notify you and the relevant supervisory authority within 72 hours.
      </P>

      <H2 dm={dm}>5. Data Retention</H2>
      <P dm={dm}>
        We retain your account and journal data for as long as your account remains active. If you delete your account, we remove your personal data from active systems within 30 days. Certain records may be retained for up to 7 years where required by financial or tax regulations. Anonymised, aggregated data may be retained indefinitely for statistical purposes.
      </P>

      <H2 dm={dm}>6. Cookies & Tracking Technologies</H2>
      <UL dm={dm} items={[
        'Essential Cookies — Required for authentication, session management, and security.',
        'Preference Cookies — Store your theme, language, and UI settings between visits.',
        'Analytics Cookies — Help us understand how the platform is used, without sharing data with advertisers.',
        'We do not use third-party advertising cookies or tracking pixels. We do not sell your data.',
      ]} />

      <H2 dm={dm}>7. Third-Party Services</H2>
      <UL dm={dm} items={[
        'Cloud Hosting — Infrastructure provider with ISO 27001 certified data centres.',
        'Payment Processing — Stripe, Inc., which is PCI-DSS Level 1 compliant.',
        'Supabase — Used for authentication and managed database services when configured.',
        'Telegram — Used only to deliver opt-in notifications. Your chat ID is stored solely for this purpose.',
        'Google Gemini — Powers AI chat and signal analysis. Conversations are not stored by Google beyond the API call.',
      ]} />

      <H2 dm={dm}>8. International Data Transfers</H2>
      <P dm={dm}>
        Our servers are primarily located in the United States and the European Union. For transfers from the EEA or UK, we rely on Standard Contractual Clauses (SCCs) approved by the European Commission to ensure adequate protection.
      </P>

      <H2 dm={dm}>9. Your Rights</H2>
      <UL dm={dm} items={[
        'Right of Access — Request a copy of all personal data we hold about you.',
        'Right to Rectification — Request correction of inaccurate or incomplete data.',
        'Right to Erasure — Request deletion of your data, subject to legal retention obligations.',
        'Right to Restriction — Request that we limit processing in certain circumstances.',
        'Right to Data Portability — Receive your journal data in CSV or JSON format.',
        'Right to Object — Object to processing based on legitimate interests.',
        'Right to Withdraw Consent — Withdraw at any time without affecting prior processing.',
        'Right to Lodge a Complaint — File a complaint with your local data protection authority.',
      ]} />

      <H2 dm={dm}>10. Children's Privacy</H2>
      <P dm={dm}>
        Our services are not directed to individuals under the age of 18. We do not knowingly collect data from minors. If we become aware that a minor has registered, we will promptly delete their account.
      </P>

      <H2 dm={dm}>11. Changes to This Policy</H2>
      <P dm={dm}>
        We may update this Privacy Policy from time to time. For material changes we will post notice on the platform at least 14 days before the change takes effect and update the "Last Updated" date above.
      </P>

      <H2 dm={dm}>12. Contact</H2>
      <P dm={dm}>
        For privacy-related enquiries, contact us at <strong>privacy@myfmjournal.com</strong> or via the Support page. We respond to privacy requests within 72 hours.
      </P>
    </>
  );
}

/* ── Terms of Service ───────────────────────────────────────────────────────── */
function TermsContent({ dm }: { dm: boolean }) {
  return (
    <>
      <H1 dm={dm}>Terms of Service</H1>
      <Updated dm={dm} />

      <P dm={dm}>
        These Terms of Service ("Terms") constitute a legally binding agreement between you ("User", "you") and <Brand dm={dm} /> ("Company", "we", "us") governing your access to and use of myfmjournal.com and any related services (collectively, the "Services"). By creating an account or using any part of our Services, you confirm that you are at least 18 years old and agree to be bound by these Terms and our Privacy Policy.
      </P>

      <H2 dm={dm}>1. Acceptance & Eligibility</H2>
      <UL dm={dm} items={[
        'You must be at least 18 years of age to register for or use our Services.',
        'By clicking "Sign Up" or accessing any feature, you accept these Terms in full.',
        'If using the Services on behalf of an organisation, you represent that you have authority to bind that entity to these Terms.',
        'We reserve the right to refuse service to any person or entity at our sole discretion.',
      ]} />

      <H2 dm={dm}>2. Description of Services</H2>
      <P dm={dm}><Brand dm={dm} /> provides an online platform for retail and professional traders, including:</P>
      <UL dm={dm} items={[
        'Trading Journal — A tool to log, annotate, and categorise trades, including screenshot uploads and psychological tagging.',
        'Performance Analytics — Metrics including win rate, expectancy, drawdown, risk-adjusted returns, and timeframe analysis.',
        'AI Trading Coach — Powered by Google Gemini. Provides contextual analysis of your journal data. Not financial advice.',
        'Economic Calendar — Aggregated high-impact macro events from multiple data sources, updated in real time.',
        'Market Session Clock — Live tracking of major trading session overlaps.',
        'Signal Analysis — Optional signal detection infrastructure for advanced users.',
        'Blog & Educational Content — Market analysis, strategy guides, and educational articles.',
      ]} />

      <H2 dm={dm}>3. Risk Disclaimer</H2>
      <P dm={dm}>
        Trading financial instruments including Forex, CFDs, cryptocurrencies, equities, and commodities involves substantial risk of loss and is not suitable for all investors. Leverage means losses can exceed your initial deposit. Nothing on this platform — including AI commentary, blog articles, signal data, or analytics — constitutes financial, investment, or trading advice. Past performance is not indicative of future results. Always consult a licensed financial adviser before making investment decisions.
      </P>

      <H2 dm={dm}>4. Account Registration & Security</H2>
      <UL dm={dm} items={[
        'You must provide accurate, current, and complete information during registration.',
        'You are solely responsible for maintaining the confidentiality of your login credentials.',
        'You must notify us immediately at support@myfmjournal.com if you suspect unauthorised access.',
        'You may not share your account with others or allow third parties to use your credentials.',
        'We are not liable for losses resulting from unauthorised use of your account.',
      ]} />

      <H2 dm={dm}>5. Subscriptions, Billing & Refunds</H2>
      <UL dm={dm} items={[
        'Certain features require a paid subscription. Fees are charged on the cycle stated at purchase (monthly or annual).',
        'All fees are stated exclusive of VAT or applicable sales taxes.',
        'Subscriptions renew automatically unless cancelled before the renewal date.',
        'Cancellation takes effect at the end of the current billing period. No partial-period refunds are issued.',
        'Refunds may be granted for billing errors or service failures. Submit requests within 7 days to support@myfmjournal.com.',
        'We reserve the right to change pricing with 30 days prior notice to active subscribers.',
      ]} />

      <H2 dm={dm}>6. Acceptable Use & Prohibited Conduct</H2>
      <P dm={dm}>You agree not to:</P>
      <UL dm={dm} items={[
        'Attempt to gain unauthorised access to any system, account, or data on the platform.',
        'Upload, transmit, or store malware, viruses, or any other harmful code.',
        'Use the platform for any unlawful purpose, including market manipulation or fraud.',
        'Scrape or systematically extract data from the platform without prior written permission.',
        'Reverse-engineer, decompile, or disassemble any part of the platform or its algorithms.',
        'Sell, sublicense, or resell access to the platform or any portion of it.',
        'Impersonate any person, entity, or trademark.',
      ]} />

      <H2 dm={dm}>7. Intellectual Property</H2>
      <P dm={dm}>
        All content, software, algorithms, designs, trademarks, and data models on the platform are owned by <Brand dm={dm} /> or its licensors and are protected by applicable intellectual property laws. You retain full ownership of the trade data you input. We do not claim any ownership over your personal trade data.
      </P>

      <H2 dm={dm}>8. Data Ownership & Export</H2>
      <UL dm={dm} items={[
        'Your journal entries, trades, and annotations are your data. We are custodians, not owners.',
        'You may export your data in CSV or JSON format at any time from the Analytics section.',
        'We do not sell, license, or share your individual trading data with third parties.',
      ]} />

      <H2 dm={dm}>9. Limitation of Liability</H2>
      <P dm={dm}>
        To the fullest extent permitted by applicable law, <Brand dm={dm} /> shall not be liable for any indirect, incidental, special, or consequential damages, including trading losses, loss of data, or business interruption. Our aggregate liability for all claims shall not exceed the greater of (a) the total fees paid by you in the twelve months preceding the claim, or (b) USD 100.
      </P>

      <H2 dm={dm}>10. Service Availability</H2>
      <P dm={dm}>
        We strive for 99.5% uptime but do not guarantee uninterrupted access. We reserve the right to modify, suspend, or discontinue any feature at any time, with at least 30 days notice before permanently discontinuing a core feature affecting paid subscribers.
      </P>

      <H2 dm={dm}>11. Termination</H2>
      <P dm={dm}>
        We may suspend or terminate your account immediately if you violate these Terms or engage in fraudulent activity. You may delete your own account at any time from your profile settings. Data export requests must be submitted within 14 days of termination.
      </P>

      <H2 dm={dm}>12. Governing Law & Disputes</H2>
      <P dm={dm}>
        These Terms are governed by applicable law. Any unresolved dispute shall be submitted to binding arbitration under the rules of a mutually agreed arbitration body. Either party may seek injunctive relief in a court of competent jurisdiction.
      </P>

      <H2 dm={dm}>13. Force Majeure</H2>
      <P dm={dm}>
        We shall not be liable for any failure or delay resulting from causes beyond our reasonable control, including acts of God, war, government action, internet outages, DDoS attacks, or third-party service failures.
      </P>

      <H2 dm={dm}>14. Amendments</H2>
      <P dm={dm}>
        We may amend these Terms at any time. For material changes, we will post notice on the platform at least 14 days before the change takes effect and update the "Last Updated" date above.
      </P>

      <H2 dm={dm}>15. Contact</H2>
      <P dm={dm}>
        For legal enquiries, contact us at <strong>legal@myfmjournal.com</strong>. For general support, reach us at <strong>support@myfmjournal.com</strong>.
      </P>
    </>
  );
}

/* ── Contact & Support ──────────────────────────────────────────────────────── */
function ContactContent({ dm }: { dm: boolean }) {
  const [form, setForm]     = useState({ user_name: '', user_email: '', subject: '', message: '' });
  const [status, setStatus] = useState<'idle' | 'sending' | 'sent' | 'error'>('idle');
  const [error, setError]   = useState('');
  const [open, setOpen]     = useState<number | null>(null);

  const border  = dm ? 'rgba(255,255,255,0.08)' : '#e5e7eb';
  const inputBg = dm ? 'rgba(255,255,255,0.04)' : '#ffffff';
  const inp: React.CSSProperties = {
    background: inputBg,
    border: `1px solid ${border}`,
    borderRadius: 8, padding: '11px 14px',
    color: dm ? '#e2e8f0' : '#0f172a',
    fontSize: 13, fontWeight: 400, outline: 'none',
    width: '100%', boxSizing: 'border-box',
    fontFamily: F, transition: 'border-color 0.2s',
  };

  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setStatus('sending'); setError('');
    try {
      const r = await fetch('/api/support/ticket', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...form, priority: 'Medium', channel: 'email' }),
      });
      if (!r.ok) throw new Error((await r.json()).error || 'Failed to send ticket');
      setStatus('sent');
      setForm({ user_name: '', user_email: '', subject: '', message: '' });
    } catch (err: any) { setStatus('error'); setError(err.message || 'Failed to send ticket'); }
  }

  const faqs = [
    { q: 'How do I reset my password?',        a: 'Click the "Forgot Password" link on the login page. A reset link will be emailed to you and expires after 1 hour.' },
    { q: 'Is my journal data private?',         a: 'Yes. All your trade entries, notes, and screenshots are encrypted at rest and in transit. Only you can access your data.' },
    { q: 'Can I export my trades?',             a: 'CSV and JSON export is available in the Analytics section. You can filter by session, date range, or strategy before exporting.' },
    { q: 'How do I import trades from MT4/5?',  a: 'Export your account history from the broker terminal as a CSV and use the Import panel in your Journal to map the columns.' },
    { q: 'Why is Trader AI not responding?',    a: 'Trader AI requires a Google Gemini API key. Ask your administrator to add GOOGLE_API_KEY to the server environment variables.' },
    { q: 'How do I delete my account?',         a: 'Submit a ticket below with the subject "Account Deletion". We process it within 5 business days and export your data first.' },
    { q: 'Is there a mobile app?',              a: 'The platform is fully responsive and works on all modern mobile browsers. A dedicated native app is on the product roadmap.' },
    { q: 'How do I cancel my subscription?',    a: 'Go to Account Settings → Subscription → Cancel Plan. Cancellation takes effect at the end of the current billing period.' },
  ];

  return (
    <>
      <H1 dm={dm}>Contact & Support</H1>
      <p style={{ fontFamily: F, fontSize: 12, color: dm ? '#64748b' : '#94a3b8', margin: '0 0 16px' }}>Last Updated: 01/01/2025</p>

      <P dm={dm}>
        Have a question, found a bug, or need help with your account? Fill in the form below and our support team will respond within 24–48 hours on business days. You can also reach us directly at <strong>support@myfmjournal.com</strong>.
      </P>

      {/* Contact cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12, margin: '24px 0 40px' }}>
        {[
          { label: 'Email',         value: 'support@myfmjournal.com',   color: '#2563eb' },
          { label: 'Response Time', value: '24 – 48 hours',              color: '#059669' },
          { label: 'Hours',         value: 'Mon – Fri · 9am – 6pm UTC', color: '#7c3aed' },
        ].map(({ label, value, color }) => (
          <div key={label} style={{ padding: '14px 16px', borderRadius: 10, border: `1px solid ${dm ? 'rgba(255,255,255,0.08)' : '#e5e7eb'}`, background: dm ? 'rgba(255,255,255,0.03)' : '#f9fafb' }}>
            <div style={{ fontFamily: F, fontSize: 9, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', color, marginBottom: 6 }}>{label}</div>
            <div style={{ fontFamily: F, fontSize: 12, color: dm ? '#e2e8f0' : '#0f172a', lineHeight: 1.5 }}>{value}</div>
          </div>
        ))}
      </div>

      <h2 style={{ fontFamily: F, fontSize: 15, fontWeight: 700, color: dm ? '#e2e8f0' : '#0f172a', margin: '0 0 16px', letterSpacing: '-0.01em' }}>
        Frequently Asked Questions
      </h2>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginBottom: 40 }}>
        {faqs.map(({ q, a }, i) => {
          const isOpen = open === i;
          return (
            <div key={i} style={{ border: `1px solid ${isOpen ? (dm ? 'rgba(37,99,235,0.4)' : '#bfdbfe') : (dm ? 'rgba(255,255,255,0.08)' : '#e5e7eb')}`, borderRadius: 10, overflow: 'hidden', transition: 'border-color 0.15s' }}>
              <button
                onClick={() => setOpen(isOpen ? null : i)}
                style={{ width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '13px 16px', background: 'transparent', border: 'none', cursor: 'pointer', textAlign: 'left', gap: 12 }}
              >
                <span style={{ fontFamily: F, fontSize: 13, fontWeight: 600, color: dm ? '#e2e8f0' : '#0f172a' }}>{q}</span>
                <span style={{ fontFamily: F, fontSize: 16, color: dm ? '#64748b' : '#9ca3af', flexShrink: 0, transform: isOpen ? 'rotate(45deg)' : 'none', transition: 'transform 0.15s', display: 'inline-block' }}>+</span>
              </button>
              {isOpen && (
                <div style={{ padding: '0 16px 14px' }}>
                  <p style={{ fontFamily: F, fontSize: 13, color: dm ? '#94a3b8' : '#374151', lineHeight: 1.8, margin: 0 }}>{a}</p>
                </div>
              )}
            </div>
          );
        })}
      </div>

      <h2 style={{ fontFamily: F, fontSize: 15, fontWeight: 700, color: dm ? '#e2e8f0' : '#0f172a', margin: '0 0 20px', letterSpacing: '-0.01em' }}>
        Submit a Support Ticket
      </h2>

      {status === 'sent' ? (
        <div style={{ padding: '36px 28px', textAlign: 'center', border: `1px solid ${dm ? 'rgba(5,150,105,0.35)' : '#6ee7b7'}`, borderRadius: 12, background: dm ? 'rgba(5,150,105,0.06)' : '#f0fdf4' }}>
          <div style={{ width: 48, height: 48, borderRadius: '50%', background: dm ? 'rgba(5,150,105,0.15)' : '#d1fae5', border: `1px solid ${dm ? 'rgba(5,150,105,0.4)' : '#6ee7b7'}`, margin: '0 auto 14px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <span style={{ color: '#059669', fontSize: 20 }}>✓</span>
          </div>
          <p style={{ fontFamily: F, fontWeight: 700, fontSize: 14, color: '#059669', marginBottom: 6 }}>Ticket Submitted.</p>
          <p style={{ fontFamily: F, fontSize: 13, color: dm ? '#94a3b8' : '#374151', marginBottom: 20, lineHeight: 1.7 }}>Our team will respond within 24–48 hours.</p>
          <button onClick={() => setStatus('idle')} style={{ background: '#2563eb', border: 'none', borderRadius: 8, padding: '10px 28px', color: '#fff', fontWeight: 700, fontSize: 12, letterSpacing: '0.08em', cursor: 'pointer', fontFamily: F }}>
            Send Another
          </button>
        </div>
      ) : (
        <form onSubmit={onSubmit} style={{ display: 'grid', gap: 14 }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div>
              <label style={{ display: 'block', fontFamily: F, fontSize: 10, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: dm ? '#64748b' : '#6b7280', marginBottom: 6 }}>Name</label>
              <input style={inp} placeholder="Your name" value={form.user_name} onChange={e => setForm(p => ({ ...p, user_name: e.target.value }))} required />
            </div>
            <div>
              <label style={{ display: 'block', fontFamily: F, fontSize: 10, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: dm ? '#64748b' : '#6b7280', marginBottom: 6 }}>Email</label>
              <input style={inp} placeholder="your@email.com" type="email" value={form.user_email} onChange={e => setForm(p => ({ ...p, user_email: e.target.value }))} required />
            </div>
          </div>
          <div>
            <label style={{ display: 'block', fontFamily: F, fontSize: 10, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: dm ? '#64748b' : '#6b7280', marginBottom: 6 }}>Subject</label>
            <input style={inp} placeholder="What is this about?" value={form.subject} onChange={e => setForm(p => ({ ...p, subject: e.target.value }))} required />
          </div>
          <div>
            <label style={{ display: 'block', fontFamily: F, fontSize: 10, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: dm ? '#64748b' : '#6b7280', marginBottom: 6 }}>Message</label>
            <textarea style={{ ...inp, minHeight: 140, resize: 'vertical' }} placeholder="Describe your issue in detail…" value={form.message} onChange={e => setForm(p => ({ ...p, message: e.target.value }))} required />
          </div>
          {status === 'error' && <p style={{ fontFamily: F, fontSize: 12, color: '#ef4444', margin: 0 }}>{error}</p>}
          <button type="submit" disabled={status === 'sending'} style={{ background: status === 'sending' ? '#93c5fd' : '#2563eb', border: 'none', borderRadius: 8, padding: '13px 24px', color: '#fff', fontWeight: 700, fontSize: 12, letterSpacing: '0.08em', cursor: status === 'sending' ? 'not-allowed' : 'pointer', transition: 'background 0.2s', fontFamily: F }}>
            {status === 'sending' ? 'Sending…' : 'Submit Ticket'}
          </button>
        </form>
      )}
    </>
  );
}

/* ── Tab param map ──────────────────────────────────────────────────────────── */
const TAB_MAP: Record<string, Section> = {
  privacy: 'Privacy Policy',
  terms:   'Terms of Service',
  contact: 'Contact & Support',
};

/* ── Page ───────────────────────────────────────────────────────────────────── */
export default function LegalPage() {
  const [active, setActive] = useState<Section>('Privacy Policy');
  const { darkMode: dm } = usePublicTheme();
  const [location] = useLocation();

  /* Sync active tab whenever the URL changes (wouter pushState or popstate) */
  useEffect(() => {
    const param = new URLSearchParams(window.location.search).get('tab') ?? '';
    const section = TAB_MAP[param.toLowerCase()];
    if (section) setActive(section);
  }, [location]);

  const pageBg   = dm ? 'rgba(8,12,16,0.97)' : '#f8fafc';
  const cardBg   = dm ? '#0d1420' : '#ffffff';
  const sidebarBg= dm ? '#0a1018' : '#ffffff';
  const border   = dm ? 'rgba(255,255,255,0.07)' : '#e5e7eb';

  const NAV: { key: Section; label: string; param: string }[] = [
    { key: 'Privacy Policy',    label: 'Privacy Policy',    param: 'privacy' },
    { key: 'Terms of Service',  label: 'Terms of Service',  param: 'terms'   },
    { key: 'Contact & Support', label: 'Contact & Support', param: 'contact' },
  ];

  function navigate(key: Section, param: string) {
    setActive(key);
    const url = new URL(window.location.href);
    url.searchParams.set('tab', param);
    window.history.pushState({}, '', url.toString());
  }

  return (
    <>
    <SEOHead
      title="Privacy Policy & Terms of Service"
      description="Read MyfmJournal's privacy policy, terms of service, and contact information. We are committed to protecting your data and your trading privacy."
      canonical="/legal"
      noindex={false}
    />
    <div style={{ minHeight: '100vh', background: pageBg, transition: 'background 0.3s' }}>
      <style>{`
        .legal-layout { display:flex; gap:32px; align-items:flex-start; }
        .legal-sidebar { flex-shrink:0; width:220px; position:sticky; top:100px; }
        .legal-mobile-tabs { display:none; }
        .legal-content { flex:1; min-width:0; }
        @media (max-width:768px) {
          .legal-layout { flex-direction:column; gap:0; }
          .legal-sidebar { display:none; }
          .legal-mobile-tabs { display:flex; overflow-x:auto; gap:4px; padding:16px 16px 0; scrollbar-width:none; }
          .legal-mobile-tabs::-webkit-scrollbar { display:none; }
          .legal-content { width:100%; }
        }
      `}</style>

      <div style={{ maxWidth: 1280, margin: '0 auto', padding: '36px 28px 80px' }}>

        {/* ── Mobile tab bar (hidden on desktop) ────────────────────────────── */}
        <div className="legal-mobile-tabs">
          {NAV.map(({ key, label, param }) => {
            const isActive = active === key;
            return (
              <button
                key={key}
                onClick={() => navigate(key, param)}
                style={{
                  fontFamily: F, fontSize: 12, fontWeight: isActive ? 700 : 500,
                  padding: '9px 16px', borderRadius: 4, border: `1px solid ${isActive ? '#2563eb' : border}`,
                  background: isActive ? (dm ? 'rgba(37,99,235,0.15)' : '#eff6ff') : (dm ? sidebarBg : '#fff'),
                  color: isActive ? '#2563eb' : (dm ? '#94a3b8' : '#374151'),
                  cursor: 'pointer', whiteSpace: 'nowrap', flexShrink: 0,
                  transition: 'all 0.15s',
                }}
              >{label}</button>
            );
          })}
        </div>

        <div className="legal-layout" style={{ marginTop: 20 }}>

          {/* ── Sidebar (desktop) ───────────────────────────────────────────── */}
          <aside className="legal-sidebar">
            <div style={{ background: sidebarBg, border: `1px solid ${border}`, borderRadius: 3, overflow: 'hidden' }}>
              <div style={{ padding: '12px 16px', borderBottom: `1px solid ${border}` }}>
                <span style={{ fontFamily: F, fontSize: 9, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', color: dm ? '#64748b' : '#9ca3af' }}>Legal & Support</span>
              </div>
              {NAV.map(({ key, label, param }) => {
                const isActive = active === key;
                return (
                  <button
                    key={key}
                    onClick={() => navigate(key, param)}
                    style={{
                      display: 'block', width: '100%', padding: '12px 16px',
                      background: isActive ? (dm ? 'rgba(37,99,235,0.12)' : '#eff6ff') : 'transparent',
                      border: 'none', borderBottom: `1px solid ${border}`,
                      textAlign: 'left', cursor: 'pointer',
                      borderLeft: isActive ? '3px solid #2563eb' : '3px solid transparent',
                      transition: 'all 0.15s',
                    }}
                  >
                    <span style={{ fontFamily: F, fontSize: 12, fontWeight: isActive ? 700 : 500, color: isActive ? '#2563eb' : (dm ? '#94a3b8' : '#374151'), transition: 'color 0.15s' }}>
                      {label}
                    </span>
                  </button>
                );
              })}
              <div style={{ padding: '12px 16px' }}>
                <div style={{ fontFamily: F, fontSize: 10, color: dm ? '#4b5563' : '#9ca3af', lineHeight: 1.6 }}>
                  Last updated<br />
                  <span style={{ color: dm ? '#64748b' : '#6b7280' }}>May 2025</span>
                </div>
              </div>
            </div>
          </aside>

          {/* ── Content card ────────────────────────────────────────────────── */}
          <div className="legal-content" style={{ background: cardBg, border: `1px solid ${border}`, borderRadius: 3, padding: '40px 48px', boxShadow: dm ? 'none' : '0 1px 4px rgba(0,0,0,0.05)' }}>
            <style>{`
              @media (max-width:600px) {
                .legal-content { padding: 24px 20px !important; }
              }
            `}</style>
            {active === 'Privacy Policy'    && <PrivacyContent    dm={dm} />}
            {active === 'Terms of Service'  && <TermsContent      dm={dm} />}
            {active === 'Contact & Support' && <ContactContent    dm={dm} />}
          </div>

        </div>
      </div>
    </div>
    </>
  );
}
