/** Terms of Service.
 *
 * Rewritten 2026-08-08. What changed and why (gap ids from the regulatory gap tracker):
 *   GAP-001  governing law now names a law, a forum and a consumer carve-out
 *   GAP-002  COPY TRADING is described — the old Terms never mentioned the product's riskiest
 *            feature at all, so the contract did not cover it
 *   GAP-003  the EU/UK 14-day cancellation right is granted, not contracted away
 *   GAP-004  the liability cap carries the carve-outs that make it survivable against a consumer
 *   GAP-009  regulatory status is stated explicitly rather than left to inference
 *
 * NOTHING HERE CLAIMS A LICENCE, AUTHORISATION OR REGISTRATION. That is deliberate and must stay
 * true: the founder's decision (2026-08-08) is to run the copy marketplace and resolve permissions
 * when it becomes operational. Silence would invite the wrong inference; a false claim would be far
 * worse. See ~/.claude/plugins/config/claude-for-legal/company-profile.md.
 */
import { H1, H2, P, UL, DL, Note, Stamp, PENDING_ENTITY, type Themed } from '../legalUI';
import TermsBoilerplate from './termsBoilerplate';

export default function Terms({ dm }: Themed) {
  return (
    <>
      <H1 dm={dm}>Terms of Service</H1>
      <Stamp dm={dm}>Last updated 8 August 2026 · These terms form a contract between you and us</Stamp>

      <Note dm={dm} tone="warn">
        <strong>Read section 3 before you use anything on this platform.</strong> We are a software
        company. We are not a broker, we are not your adviser, and we do not hold your money.
        Trading loses money for most people who try it, and copying another person's trades can lose
        money just as fast as trading yourself.
      </Note>

      <H2 dm={dm}>1. Who we are and what these terms cover</H2>
      <P dm={dm}>{PENDING_ENTITY}</P>
      <P dm={dm}>
        These terms apply every time you use the platform. If you do not accept them, do not use it.
        You must be at least 18 and legally able to enter a contract where you live. If your country
        restricts the activities described here, it is your responsibility not to use the platform.
      </P>

      <H2 dm={dm}>2. What the platform actually does</H2>
      <DL dm={dm} items={[
        ['Trading journal.', 'You record your own trades, screenshots and notes, and we show you analytics over your own history. This is the core product.'],
        ['AI commentary.', 'Automated analysis of the data you entered. It is generated by a machine, it is frequently wrong, and it is not advice.'],
        ['Market information.', 'An economic calendar, session clock and educational articles. General information, not tailored to you.'],
        ['Signals.', 'We may publish trade setups, including to Telegram. They are published for education and illustration. They are not personal recommendations and are not tailored to your circumstances, means or objectives. We do not know your situation.'],
        ['Copy trading.', 'You may connect your own broker account and choose to follow another user ("a provider"). When you do, orders placed by that provider are transmitted automatically to your broker account, sized by the settings you choose. You may stop at any time.'],
      ]} />

      <H2 dm={dm}>3. Risk, and the limits of what we are</H2>
      <Note dm={dm} tone="warn">
        Trading foreign exchange, CFDs, cryptocurrencies, shares and commodities carries a high risk
        of losing money. Leverage magnifies losses as much as gains, and with some instruments you
        can lose more than you deposited. Most retail traders lose money. Never risk money you cannot
        afford to lose.
      </Note>
      <DL dm={dm} items={[
        ['Nothing here is financial advice.', 'Not the AI commentary, not the analytics, not the articles, not the signals, and not anything a provider does. None of it is a personal recommendation and none of it takes account of your circumstances.'],
        ['We are not authorised or regulated.', 'We do not hold, and do not claim to hold, any financial services licence, authorisation or registration in any country. We are a software provider. If you need advice, use someone licensed to give it where you live.'],
        ['We never hold your money.', 'You connect your own account at your own broker. Your funds stay with that broker throughout, and your relationship with them is governed by their terms, not ours.'],
        ['We do not execute anything ourselves.', 'Where copy trading is enabled, we transmit instructions to your broker. Whether an order is accepted, at what price, and with what slippage, spread, fee or delay is determined by your broker and the market — not by us.'],
      ]} />

      <H2 dm={dm}>4. Copy trading, in particular</H2>
      <P dm={dm}>
        Copy trading is the highest-risk thing you can do on this platform. If you use it, you are
        choosing to let another person's decisions move your money, automatically, without you
        approving each trade.
      </P>
      <DL dm={dm} items={[
        ['You decide, and you remain responsible.', 'Choosing a provider is your decision alone. We do not select, vet, endorse, rank by merit, or recommend any provider, and we do not supervise how any of them trade.'],
        ['Providers are not our staff or agents.', 'They are users. They may stop, change strategy, take far more risk than before, or lose money badly, at any time and without notice to you or to us.'],
        ['Past performance means nothing about the future.', 'Where figures are shown they describe what already happened on that account. They are not a forecast, not a promise, and not a reason to expect a similar result.'],
        ['Set your own limits and watch them.', 'Position sizing, maximum drawdown and loss limits are yours to set. They reduce risk; they do not remove it. Fast markets, gaps and outages can carry you past any limit you set.'],
        ['It can fail.', 'Connectivity, broker rejections, latency and outages mean a copied order may arrive late, at a worse price, in part, or not at all.'],
      ]} />

      <H2 dm={dm}>5. Your account</H2>
      <UL dm={dm} items={[
        'Give accurate registration details and keep them current.',
        'Keep your credentials secret — you are responsible for everything done through your account.',
        'Tell us immediately at support@tradeandjournal.com if you suspect someone else has access.',
        'Do not share your account, and do not let anyone else use your credentials.',
        'Any broker credentials or API keys you connect are used only to operate the features you switched on.',
      ]} />

      <H2 dm={dm}>6. Paying, cancelling and refunds</H2>
      <P dm={dm}>Some features need a paid subscription. Full terms are in our Cancellation &amp; Refunds policy; the essentials are:</P>
      <UL dm={dm} items={[
        'Fees are charged on the cycle shown at purchase and renew automatically until you cancel.',
        'You can cancel at any time, and cancellation takes effect at the end of the period you have paid for.',
        'If you are a consumer in the EU or UK you have 14 days to change your mind — see the Cancellation & Refunds policy, which explains the one situation where that right ends early.',
        'We give at least 30 days notice before a price change affecting you.',
      ]} />

      <H2 dm={dm}>7. Acceptable use</H2>
      <P dm={dm}>
        The full list is in our Acceptable Use policy. In short: do not break the law with it, do not
        attack it, do not scrape it, do not resell it, and do not use it to mislead other users —
        including by publishing false performance or presenting yourself as licensed when you are not.
      </P>

      <H2 dm={dm}>8. Your content and your data</H2>
      <UL dm={dm} items={[
        'Your journal entries, trades and notes are yours. We hold them for you; we do not own them.',
        'You can export your data at any time, and we do not sell your individual trading data.',
        'You give us only the permission we need to run the service for you — storing, processing and displaying your content back to you.',
        'The platform itself, its design, code and branding remain ours.',
      ]} />

      <TermsBoilerplate dm={dm} />
    </>
  );
}
