"""
AI chart validation via Gemini.
Stub: always returns True (approved) when no API key is configured.
When GEMINI_API_KEY is set, sends chart image for visual review.
Non-blocking — a Gemini failure never kills a signal.
"""

import logging
from pathlib import Path
from config.settings import settings

log = logging.getLogger(__name__)


async def validate_chart(chart_path: str | None) -> bool:
    """
    Returns True if Gemini approves the chart (or key is absent).
    chart_path: filesystem path to the PNG generated by chart_generator.
    """
    if not settings.gemini_api_key or not chart_path:
        return True

    try:
        return await _call_gemini(chart_path)
    except Exception as exc:
        log.warning(f"[ai_validator] Gemini error (approving anyway): {exc}")
        return True


async def _call_gemini(chart_path: str) -> bool:
    """Send chart image to Gemini for visual signal review."""
    import google.generativeai as genai
    genai.configure(api_key=settings.gemini_api_key)
    model = genai.GenerativeModel("gemini-1.5-flash")

    image_data = Path(chart_path).read_bytes()
    response = model.generate_content([
        {"mime_type": "image/png", "data": image_data},
        "Does this chart show a clear and valid trading signal with proper "
        "market structure? Reply with YES or NO only.",
    ])
    text = response.text.strip().upper()
    approved = text.startswith("YES")
    log.info(f"[ai_validator] Gemini: {text} → {'approved' if approved else 'rejected'}")
    return approved
